name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Run unit tests
        run: mvn -B -Dtest='*Test' test
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
      - name: Checkout
        run:  actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: "maven"
      - name: Run quality
        run: mvn verify -DskipTests
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: order-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Run integration tests
        run: mvn -B -Dtest='*IntegrationTest' test